[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
remaining_account_read = "AGJTaqNYeuFnT5P5VBej8cFtwzkX9HD1W2SiYRD2sRY1"

[programs.localnet]
remaining_account_read = "8CNhsS9KaAhuy2TdtLQowZNbhHQfL34CyHTJPjJSXAHP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
